---
manifestPath: /usr/share/keskos/installer/package-manifest.json
defaultBrowser: librewolf
applyBrowserTheme: false
removeOtherBrowsersAfterInstall: false
defaultDesktopProfile: kesk_default
defaultBundles: []
defaultAddons: []
extraPackages: []
forceEnabledFeatures:
  - quickshell_topbar
  - kde_bottom_taskbar
  - plasma_theme
  - window_borders
  - sddm_theme
  - plymouth
forceDisabledFeatures:
  - browser_startpage
choicesOutput: /tmp/keskos-install-choices.json
packageListOutput: /tmp/keskos-final-packages.txt
targetChoicesPath: /var/lib/keskos/install-choices.json
targetPackageListPath: /var/lib/keskos/final-packages.txt
