---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "keskos-plymouth-boot-status.service"
    action: "enable"
    mandatory: false
  - name: "keskos-plymouth-min-duration.service"
    action: "enable"
    mandatory: false
  - name: "systemd-resolved.service"
    action: "enable"
    mandatory: false
  - name: "graphical.target"
    action: "enable"
    mandatory: false
  - name: "qemu-guest-agent.service"
    action: "enable"
    mandatory: false
