---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 18.0
  requiredRam: 2.0
  check:
    - storage
    - ram
    - power
    - screen
  required:
    - storage
    - ram
    - screen

geoip:
  style: none
  url: https://geoip.kde.org/v1/ubiquity
  selector: CountryCode
